spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: obokbosok.kr@gmail.com
    password: Obsb1234!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true